title: "Aylin Wang"
logo: "/images/bio_photo.jpg?raw=true"
description: >
  Welcome to My Profile — a space where data tells stories and insights spark action.
  <br><br>
  I explore how data empowers bold strategies and sparks breakthrough ideas.
  <br><br>
  <a href="https://www.linkedin.com/in/jialin1995/" target="_blank">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal

show_downloads: false
google_analytics: ""  # Add your GA tracking ID if needed, e.g., "UA-XXXXXXXXX-X"
author:
  name: "Aylin Wang"
  email: "wjialin1995@gmail.com"

# Build settings
markdown: kramdown
